import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/header";
import { ClerkProvider } from '@clerk/nextjs';

export const metadata: Metadata = {
  title: "LinkedIn Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="min-h-screen flex flex-col">
          <header className="sticky top-0 bg-white z-50">
            <Header />
          </header> 
          <main className="bg-[#F4F2ED] flex-1 w-full">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
